### ISSUE TITLE
So excited to find this

### ISSUE THREAD

**Issue by OldPotatoes** [vgribok/cdk-populate-dynamodb-table#1]
Sorry to abuse the issue system to send a message, but I just wanted to thank you for putting this online. I wanted to write C# that populated a DynamoDB with CDK and I can't find any documentation or tutorials anywhere that does this in C#. Even AWS seem to have forgotten to put anything in the SDK docs.

Stepping through your code, the data structure leaves me scratching my head. I *think* that it's an array of dictionaries of key value pairs containing a dictionary of dictionaries of key value pairs, but 🤷. I'm just going to use your PrepItems code and look the other way.

**Comment by vgribok** [comment]
Could not even remember writing this! But you are right, that is an array of dictionaries, where each dictionary is a DDB item (record). Since DDB is schema-less, each item has to have not only values, but also field (attribute) names, hence each record is a dictionary. [GeneratePutData()](https://github.com/vgribok/cdk-populate-dynamodb-table/blob/2c9b0207c8804c83fc454122c48d870d1cceed37/src/CdkDdbPopulate/CdkDdbPopulateStack.cs#L22) is a way to de-boilerplate main stack code so it would be possible to simply specify the DDB table and data items to insert.
